sudo: required
dist: trusty
language: cpp

compiler: gcc

before_install:
# -  sudo apt-get remove binutils-arm-none-eabi gcc-arm-none-eabi
 - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y # -qq is for travis CI
 - sudo apt-get update
 - sudo apt-get install gcc-arm-embedded u-boot-tools libboost1.55-all-dev -y

before_script:
# - cd ev3rt-git/ev3rt-hrp2-base
# - git submodule init
# - git submodule update
 - cd cfg
 - make
 - cd ../base-workspace
 - make app=loader
 - cd ../sdk/workspace

script: make app=helloev3

before_deploy:
  - git config --local user.name "JarakParal"
  - git config --local user.email "paral.jarek@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - zip -r RB3rt.zip .
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file: "RB3rt.zip"
  skip_cleanup: true

